# Generated by Django 5.0.7 on 2024-07-12 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_id', models.CharField(help_text='Example QID27', max_length=10, unique=True)),
                ('question', models.TextField(help_text='Enter your Question')),
                ('opt1', models.CharField(help_text='Enter Option 1 for question ', max_length=255)),
                ('opt2', models.CharField(help_text='Enter Option 2 for question ', max_length=255)),
                ('opt3', models.CharField(help_text='Enter Option 3 for question ', max_length=255)),
                ('opt4', models.CharField(help_text='Enter Option 4 for question ', max_length=255)),
                ('answers', models.TextField(help_text='Enter Answer for Question')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_id', models.CharField(help_text='Example RID27', max_length=10, unique=True)),
                ('response_mail', models.EmailField(help_text='Enter Email of Respondent', max_length=254, unique=True)),
                ('response_by', models.CharField(help_text='Enter Name of Respondent', max_length=100)),
                ('response_at', models.DateTimeField(auto_now_add=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_id', models.CharField(help_text='Example FID27', max_length=10, unique=True)),
                ('form_name', models.CharField(help_text='Enter name of Form', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(help_text='Enter name of Form Creator', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionsInForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qif_id', models.CharField(help_text='Example QFID27', max_length=10, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('form_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.forms')),
                ('question_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.questions')),
            ],
        ),
    ]
