# Generated by Django 5.0.7 on 2024-07-12 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forms',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='forms',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='questionsinforms',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='questionsinforms',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='responses',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='responses',
            name='is_superuser',
        ),
    ]
