# Generated by Django 5.0.7 on 2024-07-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_forms_is_staff_remove_forms_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responses',
            name='response_by',
        ),
        migrations.AddField(
            model_name='responses',
            name='response',
            field=models.CharField(default=1, help_text='Response String', max_length=1000),
            preserve_default=False,
        ),
    ]
