# Generated by Django 5.0.7 on 2024-07-14 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_responses_response_by_responses_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsinforms',
            name='form_fk',
            field=models.ForeignKey(help_text='Select form Creator', on_delete=django.db.models.deletion.CASCADE, to='users.forms'),
        ),
    ]
